name: dotnet-build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish CdAudioWpfUi project
        run: |
          dotnet publish ./CdAudioWpfUi/CdAudioWpfUi.csproj `
            -c Release `
            -f net6.0-windows `
            -r win-x64 `
            --self-contained false `
            /p:PublishReadyToRun=true

      - name: Extract Assembly Info from CSPROJ
        id: meta
        run: |
          [xml]$csproj = Get-Content ./CdAudioWpfUi/CdAudioWpfUi.csproj
          $title = $csproj.Project.PropertyGroup.AssemblyTitle
          $version = $csproj.Project.PropertyGroup.AssemblyVersion
          $shortVersion = ($version -split '\.')[0..2] -join '.'
          $artifactName = "${title}V${shortVersion}"
          echo "ZIP_BASE=$artifactName" >> $env:GITHUB_ENV

      - name: Remove .pdb files from publish output
        run: |
          $publishDir = "CdAudioWpfUi\bin\Release\net6.0-windows\win-x64\publish"
          if (Test-Path $publishDir) {
            Get-ChildItem $publishDir -Recurse -Filter *.pdb | Remove-Item -Force
          } else {
            Write-Error "Publish directory '$publishDir' not found."
          }

      - name: Upload publish folder as artifact (auto-zipped by GitHub)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_BASE }}
          path: CdAudioWpfUi/bin/Release/net6.0-windows/win-x64/publish
